student=[]
number=[1,2,3,4,5]
print("initial list:",student)
student.append('Alice')
student.append('bob')
student.append('charlie')
print("list after appending the names:",student)
student.insert(1,'david')
print("After inserting david at index 1",student)
name=['eva','francis']
student.extend(name)
print("After extending",student)
print("count of bob",student.count('bob'))
print("index of charlie is:",student.index('charlie'))
student.remove('eva')
print("After removing eva:",student)
print("poped item is:",student.pop())
student.sort()
print("sorted list:",student)
student.reverse()
print("reversed list:",student)
print("first 3 elements of the list:",student[0:3])
print("length of the list",len(student))
student2=student.copy()
print("copy of the list is :",student2)
student.clear()
print(student)
print("sum of elements of the list is:",sum(number))
print("minimum element of the list is:",min(number))
print("maximum element of the list is :",max(number))
